"""Add enhanced document fields and query history

Revision ID: 706eaea67451
Revises: 8a5189b7de66
Create Date: 2025-07-07 17:49:43.454476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706eaea67451'
down_revision = '8a5189b7de66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('relevant_documents', sa.Text(), nullable=True),
    sa.Column('processing_time', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_id'), 'query_history', ['id'], unique=False)
    op.create_index(op.f('ix_query_history_session_id'), 'query_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.add_column('document_embeddings', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processed_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'processed_chunks')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_hash')
    op.drop_column('document_embeddings', 'chunk_size')
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_session_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_id'), table_name='query_history')
    op.drop_table('query_history')
    # ### end Alembic commands ###